### ISSUE TITLE
Should we disable warnings for strong-named assemblies? (CA2210)

### ISSUE THREAD

**Issue by j2jensen** [HealthCatalyst/Fabric.SharedSettings#4]
According to [the docs](https://msdn.microsoft.com/en-us/library/ms182127.aspx):

>The strong name protects clients from unknowingly loading an assembly that has been tampered with. Assemblies without strong names should not be deployed outside very limited scenarios. If you share or distribute assemblies that are not correctly signed, the assembly can be tampered with, the common language runtime might not load the assembly, or the user might have to disable verification on his or her computer. An assembly without a strong name has from the following drawbacks:
> - Its origins cannot be verified.
> - The common language runtime cannot warn users if the contents of the assembly have been altered.
> - It cannot be loaded into the global assembly cache.

Considering the way that we go about distributing our software, is this ever likely to be an issue? We could create a section in [the wiki](https://github.com/HealthCatalyst/Fabric.SharedSettings/wiki) instructing people how to sign their assemblies, but it seems like a lot of work if there's no reason to believe that people could be tampering with our assembly.

**Comment by j2jensen** [comment]
According to @johnrulon 
> I believe we should disable that warning. Industry suggests not to strong sign for the sake of tamper prevention, but rather Code sign with Authenticode. There are cases where we do have to strong sign (when a dll is installed into the GAC being one), but I don't think we should enforce this CA warning.

**Comment by johnrulon** [comment]
One point of reference: [Still strong naming your assemblies?](https://www.pedrolamas.com/2016/03/01/still-strong-naming-your-assemblies-you-do-know-its-2016-right/)
